baseURL = 'https://antoniojnr.github.io/'
languageCode = 'pt-br'
title = 'Antonio Dias'
theme = 'hugo-book'

[params]
  BookSection = 'docs'
  BookNextPrev = false
[markup.goldmark.renderer]
  unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'